
NO_REFLECTED_DAMAGE = 0

ATTACK = 'attack'
ATTACK_CONDITIONAL = 'attack_conditional'
CARD_ACROSS = 'card_across'
CARD_ADJACENT = 'card_adjacent'
CARD_LOWEST_HP = 'card_lowest_hp'
CARD_MANIPULATION = 'card_manipulation'
CONDITION = 'condition'
CONDITION_TYPE = 'condition_type'
CONDITION_PARAMETER = 'condition_parameter'
DAMAGE_MITIGATION = 'damage_mitigation'
DAMAGE = 'damage'
DEMON = 'demon'
EFFECT_TYPE = 'effect_type'
ENEMY = 'enemy'
ENEMY_HERO = 'enemy_hero'
EXILE = 'exile'
FOREST = 'forest'
HP = 'hp'
ICE = 'ice'
IMMUNE = 'immune'
LIGHTNING = 'lightning'
MOUNTAIN = 'mountain'
NO_HEALS = 'no_heals'
OTHER = 'other'
SACRIFICE = 'sacrifice'
SEAL = 'seal'
SELF = 'self'
SWAMP = 'swamp'
TARGET = 'target'
TURN = 'turn'
TRAP = 'trap'

IMMUNITY_EFFECT_TYPES = (ICE, LIGHTNING, TRAP, SEAL, SACRIFICE)
DAMAGE_TO_HERO_EFFECT_TYPES = (ATTACK, ENEMY_HERO)
